# Generated by Django 5.1.1 on 2024-09-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('euro', 'EURO'), ('gbp', 'GBP'), ('ngn', 'NGN')], default='ngn', max_length=75),
        ),
    ]
