# Generated by Django 5.1.1 on 2024-09-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_alter_itineraryitem_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryitem',
            name='item_type',
            field=models.CharField(choices=[('transport', 'Transport'), ('lodge', 'Lodge'), ('activity', 'Activity')], max_length=75),
        ),
    ]
