# Generated by Django 5.1.1 on 2024-09-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_alter_itineraryitem_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_type',
            field=models.CharField(choices=[('flight', 'Flight'), ('bus', 'Bus'), ('train', 'Train'), ('ship', 'Ship'), ('car', 'Car')], max_length=100),
        ),
    ]
