# Generated by Django 4.1.2 on 2024-09-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_destination_delete_expensecategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='location',
        ),
    ]
